spring:
  datasource:
    url: jdbc:h2:file:./data/tennis_db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: never

server:
  port: 8081

# 添加 JWT 配置
jwt:
  secret: a592f94d7a431724d64266ba3fae5ed5a7120e9f6264ea3d4d37acf2f0d569b05451930e4e1f0a987e5557740383901da5de0b4cdc12d2f4d0e2c4d2d8b4f9e6
  expiration: 86400000  # 24小時，以毫秒為單位 